#!/bin/bash
# JARVIS AI Assistant - Startup Script

echo "=================================================="
echo "  🤖 JARVIS AI PERSONAL ASSISTANT"
echo "=================================================="
echo ""
echo "Starting JARVIS in 2 terminals..."
echo ""
echo "Make sure you have:"
echo "  ✓ Python 3.13+"
echo "  ✓ Virtual environment activated"
echo "  ✓ Dependencies installed"
echo ""
echo "=================================================="
echo "  TERMINAL 1: Backend AI System"
echo "=================================================="
echo "cd c:\Users\santo\ai-assistant"
echo "python backend/dashboard_api.py"
echo ""
echo "→ Backend will start on http://localhost:5000"
echo "→ API endpoints ready"
echo "→ 12-layer system initialized"
echo ""
echo "=================================================="
echo "  TERMINAL 2: Frontend Dev Server"
echo "=================================================="
echo "cd c:\Users\santo\ai-assistant"
echo "python frontend_server.py"
echo ""
echo "→ Frontend will start on http://localhost:8080"
echo "→ Dashboard ready"
echo "→ Connect to backend on 5000"
echo ""
echo "=================================================="
echo "  BROWSER"
echo "=================================================="
echo "Open: http://localhost:8080"
echo ""
echo "→ Jarvis Dashboard loads"
echo "→ Select mode (Chat/Command/Goal/Analytics/Trading)"
echo "→ Type your request"
echo "→ Watch AI process through 12 layers"
echo "→ See response with complexity/intent info"
echo ""
echo "=================================================="
echo "  MODES"
echo "=================================================="
echo "💬 Chat        - Natural conversation"
echo "⚡ Commands    - System commands"
echo "🎯 Goals       - Multi-step planning"
echo "📊 Analytics   - Data analysis"
echo "📈 Trading     - Market analysis"
echo ""
echo "=================================================="
echo "  QUICK ACTIONS"
echo "=================================================="
echo "📋 Daily Briefing  - Today's agenda"
echo "🔔 Reminders       - Your reminders"
echo "🧠 Memory          - Learned patterns"
echo ""
echo "=================================================="
echo "  KEYBOARD SHORTCUTS"
echo "=================================================="
echo "Enter              - Send message"
echo "Ctrl+K             - Focus input"
echo "Ctrl+Space         - Voice control (ready)"
echo ""
echo "=================================================="
echo "  API ENDPOINTS"
echo "=================================================="
echo "POST /api/request           - Send request"
echo "GET /api/health             - Health check"
echo "GET /api/system/status      - System info"
echo "GET /api/system/knowledge   - Learned patterns"
echo ""
echo "=================================================="
echo "  TROUBLESHOOTING"
echo "=================================================="
echo ""
echo "❌ Connection refused?"
echo "   → Check backend is running on port 5000"
echo "   → Run: python backend/dashboard_api.py"
echo ""
echo "❌ Frontend won't load?"
echo "   → Check frontend server on port 8080"
echo "   → Run: python frontend_server.py"
echo ""
echo "❌ 503 Service Unavailable?"
echo "   → Backend not responding"
echo "   → Check backend logs"
echo ""
echo "❌ AI layers not loading?"
echo "   → Check Python imports"
echo "   → Verify virtual environment"
echo ""
echo "=================================================="
echo "  STATUS CHECK"
echo "=================================================="
echo ""
echo "Backend Health:"
echo "  curl http://localhost:5000/api/health"
echo ""
echo "System Status:"
echo "  curl http://localhost:5000/api/system/status"
echo ""
echo "=================================================="
echo "  DEPLOYMENT"
echo "=================================================="
echo ""
echo "To deploy to Netlify:"
echo ""
echo "1. Install CLI:"
echo "   npm install netlify-cli -g"
echo ""
echo "2. Initialize:"
echo "   netlify init"
echo ""
echo "3. Set environment:"
echo "   netlify env:set OPENAI_API_KEY your_key"
echo ""
echo "4. Deploy:"
echo "   netlify deploy"
echo ""
echo "=================================================="
echo "  DOCUMENTATION"
echo "=================================================="
echo ""
echo "📖 README.md              - Quick start"
echo "📖 JARVIS_SUMMARY.md      - System overview"
echo "📖 DEPLOYMENT_GUIDE.md    - Production guide"
echo "📖 SYSTEM_ARCHITECTURE.md - Technical details"
echo ""
echo "=================================================="
echo ""
echo "🚀 Ready to start? Open 2 terminals and follow above!"
echo ""
echo "💡 Tip: Check the logs in each terminal for real-time feedback"
echo ""
echo "=================================================="
echo "  Welcome to JARVIS! 🤖"
echo "=================================================="
